spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. NEW SECURE DIRECTORY AUTH ROUTE (Points to Node.js + LDAP Stack)
        - id: directory-auth
          uri: ${AUTH_SERVICE_URL:http://ticket-registration-service:5000}
          predicates:
            - Path=/api/v1/auth/**

        # 2. OTP ENGINE ROUTE (Kept on Notification service if needed)
        - id: notification-otp
          uri: http://tbs-notification-service:8082
          predicates:
            - Path=/api/v1/otp/**

        # 3. PROTECTED MICROSERVICE ROUTE
        - id: booking-service
          uri: http://ticket-booking-service:8081
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - AuthenticationFilter  # Runs token validation checks
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"  # Points straight to your React dev port
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
jwt:
  secret: "YOUR_32_BYTE_LONG_SECURE_HMAC_ENCRYPTION_SECRET_KEY"
  expiration: 86400000 # Token valid for 24 Hours
