server:
  port: 8080
spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  cloud:
    gateway:
      routes:
        - id: booking_route
          uri: http://booking-service:8080
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
