server:
  port: 8080

spring:
  application:
    name: booking-service

  datasource:
    # 🌟 TARGET: Points directly to the 'postgres' database engine on your host machine
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/postgres?options=-c%20search_path=public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:system}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # 🌟 Hibernate will now build tables directly inside ticket_db
    show-sql: true
    properties:
      # 🌟 SCHEMA MAPPING: Forces Hibernate to execute transactions in 'public'
      hibernate.default_schema: public

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ticket-fulfillment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ticket.booking.model"
