package com.ticket.booking.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.Instant;

@Entity
@Table(name = "ticket_orders")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TicketOrder {

    @Id
    private String orderId; // Using the UUID generated by our BookingService

    @Column(nullable = false)
    private String userId;

    @Column(nullable = false)
    private String eventId;

    @Column(nullable = false)
    private String seatId;

    @Column(nullable = false)
    private String status; // e.g., "PENDING_PAYMENT", "CONFIRMED", "CANCELLED"

    @Column(nullable = false)
    private Instant createdAt;

    private Instant updatedAt;
}
