exports.validateBody = (schema) => {
  return (req, res, next) => {
    const result = schema.safeParse(req.body);

    if (!result.success) {
      // Pick the first error string generated by Zod to return neatly to the frontend UI
      const primaryMessage = result.error.errors[0].message;
      return res.status(400).json({ error: primaryMessage });
    }

    // Override body with validated and cleaned data strings
    req.body = result.data;
    next();
  };
};
