# main.py
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field
from rag.indexer import seed_database_and_vectors
from agents.orchestrator import run_agent_loop

# Initialize the FastAPI application context
app = FastAPI(
    title="Lightweight Movie Chat AI Service",
    description="A CPU-optimized FastAPI microservice utilizing ChromaDB RAG and Ollama local LLM execution pipelines.",
    version="1.0.0"
)

# --- Pydantic Data Validation Models ---
class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        description="The user query or prompt string containing movie descriptions, vibes, or scheduling questions.",
        examples=["Find me a space movie with deep cosmic vibes"]
    )

class ChatResponse(BaseModel):
    reply: str = Field(..., description="The context-aware response generated by the local agent orchestration framework.")

class StatusResponse(BaseModel):
    status: str = Field(..., description="Operational status message response string.")


# --- Lifecycle Events ---
@app.on_event("startup")
async def startup_event():
    """Initializes and seeds database instances automatically when the microservice container spins up."""
    print("Initializing Movie Chat AI Service components...")
    try:
        seed_database_and_vectors()
        print("Database verification hook completed successfully.")
    except Exception as e:
        print(f"CRITICAL ERROR: Failed to seed initialization sequence: {e}")


# --- API Endpoint Handlers ---
@app.get("/", tags=["Health"])
async def root():
    """Simple API root heartbeat check to verify connection viability."""
    return {"status": "healthy", "service": "Movie-RAG-Agent-Service"}


@app.post(
    "/chat",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
    tags=["Agent Logic"]
)
async def chat_endpoint(payload: ChatRequest):
    """Processes natural language user requests against the vector engine through a unified agent loop."""
    user_msg = payload.message.strip()

    if not user_msg:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Chat prompt message cannot be empty or solely whitespace formatting."
        )

    try:
        # Route query to your local orchestrator engine block
        ai_reply = run_agent_loop(user_msg)
        return ChatResponse(reply=ai_reply)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"System Error Encountered during inference: {str(e)}"
        )


@app.post(
    "/seed",
    response_model=StatusResponse,
    status_code=status.HTTP_200_OK,
    tags=["Database Maintenance"]
)
async def trigger_database_seed():
    """Manually re-trigger database mapping validations or seed missing record entries on demand."""
    try:
        seed_database_and_vectors()
        return StatusResponse(status="ChromaDB vector space verified/seeded successfully.")
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database operational failure occurred: {str(e)}"
        )
